package com.example.riichit

object Drawables {
    val tiles = arrayOf(
        R.drawable.man_1,
        R.drawable.man_2,
        R.drawable.man_3,
        R.drawable.man_4,
        R.drawable.man_5,
        R.drawable.man_6,
        R.drawable.man_7,
        R.drawable.man_8,
        R.drawable.man_9,
        R.drawable.pin_1,
        R.drawable.pin_2,
        R.drawable.pin_3,
        R.drawable.pin_4,
        R.drawable.pin_5,
        R.drawable.pin_6,
        R.drawable.pin_7,
        R.drawable.pin_8,
        R.drawable.pin_9,
        R.drawable.sou_1,
        R.drawable.sou_2,
        R.drawable.sou_3,
        R.drawable.sou_4,
        R.drawable.sou_5,
        R.drawable.sou_6,
        R.drawable.sou_7,
        R.drawable.sou_8,
        R.drawable.sou_9,
        R.drawable.wind_east,
        R.drawable.wind_south,
        R.drawable.wind_west,
        R.drawable.wind_north,
        R.drawable.dragon_red,
        R.drawable.dragon_white,
        R.drawable.dragon_green,
        R.drawable.closed
    )
}