package com.example.riichit

val yakuHanCost = mapOf("chantaiayo" to 2,
        "chiitoitsu" to 2,
        "chinitsu" to 6,
        "dora" to 1,
        "double riichi" to 2,
        "iipeikou" to 1,
        "ippatsu" to 1,
        "ittsu" to 2,
        "junchan taiayo" to 3,
        "haitei raoyue" to 1,
        "honitsu" to 0,
        "honroutou" to 2,
        "menzenchin tsumohou" to 1,
        "pinfu" to 1,
        "riichi" to 1,
        "rinshan kaihou" to 1,
        "ryanpeikou" to 3,
        "sanankou" to 2,
        "sankantsu" to 2,
        "sanshoku doujun" to 2,
        "sanshoku doukou" to 2,
        "shousangen" to 2,
        "tanyao" to 1,
        "yakuhai" to 1)

val yakumanHanCost = mapOf("13-wait kokushi musou" to 26,
        "chinroutou" to 13,
        "chuuren poutou" to 13,
        "daisangen" to 13,
        "daisuushii" to 26,
        "kokushi musou" to 13,
        "pure chuuren poutou" to 26,
        "ryuuiisou" to 13,
        "shousuushii" to 13,
        "suuankou" to 13,
        "suuankou tanki" to 26,
        "suukantsu" to 13,
        "tenhou" to 13,
        "tsuuiisou" to 13)